### ISSUE TITLE
[Bug]: Divine Descent Checklist!

### ISSUE THREAD

**Issue by puncrafter** [puncrafter/Modpack-Issue-Tracker#22]
### Modpack

Divine Descent

### Describe the bug

- [ ] Do the JEI Trimming
- [ ] Fix Essential incompatibility by switching from ThiccEntities to whatever else I'm using
  - [ ] This would probably also fix the healing-upon-relogging bug?
- [ ] The last clause of the Wither summoning script would probably mess up already spawned withers
- [ ] Make cake heal. Or perhaps another effect?
- [ ] Replace the block of sulfur in the trash heap
- [ ] Buff broken bottle
- [ ] Mod that adds backups
- [ ] Add S&G guns to the copper/brass armor bonus
  - [ ] Attempt to make the bonus damage become bonus healing when using biotic rounds? Or at least nullify the bonus damage.
- [ ] Attempt to add recipes for the S&G minigun drum
- [ ] Starpath focus crashes when going into the void or above the build limit. In theory, I could try to fix this by making arrows fired from certain areas fail, or futzing around with entitydata. I hope I don't have to disable the item entirely!
- [ ] Consider adding that postgame you were thinking of. No pressure, though.
- [ ] Double-check on these. https://github.com/puncrafter/Modpack-Issue-Tracker/issues/6
